config/routes.rb
Uberzeit::Application.routes.draw do

  year_month_team_id_constraints = {year: /\d+/, month: /\d+/, team_id: /\d+/}

  root :to => 'sessions#new'


  # session stuff
  resource :session, only: [:new, :create, :destroy] do
    put '/language', action: :change_language
  end

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/logout', to: 'sessions#destroy', as: 'logout'


  # users scope
  resources :users do
    member do
      put '/activate', to: 'users#activate', as: 'activate'
      put '/deactivate', to: 'users#deactivate', as: 'deactivate'
    end
    resource :password, only: [:edit, :update]

    resources :recurring_entries, except: [:show, :index]

    resources :absences do
      collection do
        get '/year/:year', to: 'absences#index', as: 'year'
        resources :time_entries, controller: :absence_time_entries, as: :absence_time_entries, only: :create
      end
    end

    get '/comparison/date/:date', to: 'comparison#show', as: :comparison

    resources :time_entries, except: [:show] do
      collection do
        get '/date/:date', to: 'time_entries#index', as: :show_date
        put '/date/:date/stop-timer', to: 'time_entries#stop_timer'

        get '/date/:date/summary', to: 'time_entries#summary_for_date'
      end
    end

    resources :employments
    resources :activities do
      collection do
        get '/date/:date', to: 'activities#index', as: :show_date
      end
    end

    resources :roles, only: [:index, :new, :create, :destroy]
  end

  # management
  resources :public_holidays, except: [:show]
  resources :time_types, except: [:show]
  resources :adjustments, except: [:show]
  resources :projects, except: [:show]
  resources :activity_types, except: [:show]
  resource :configuration, only: [:edit, :update]


  # reporting
  namespace :reports do
    get '/overview/users/:user_id', to: 'overview#index', as: :overview
    get '/work/users/:user_id', to: 'my_work#show', as: :my_work
    get '/work', to: 'work#show', as: :work
    get '/absences', to: 'absence#show'
    get '/absences-calendar', to: 'absence#calendar', as: :absences_calendar
    get '/vacation', to: 'vacation#show'

    namespace :activities do
      get '/billability(/:date)', to: 'billability#index', as: :billability
      get '/billing', to: 'billing#index', as: :billing
      get '/filter', to: 'filter#index', as: :filter
      get '/detailed', to: 'detailed#index', as: :detailed
    end
  end

  resources :teams, except: :show

  resources :customers, except: :show

  # API
  mount API::User => '/api'
  mount API::App => '/api/app'
end

app/views/shared/_absences_tooltip.html.erb
<%
  edit = can?(:manage, Absence) if local_assigns[:edit].nil?
%>
<div class='event'>
<% absences.each do |absence| %>
  <h1>
    <%= icon_for_time_type(absence.time_type).gsub('"', '\'') %> <%= absence.time_type.name %>
  </h1>
  <p class='date-range'><%= absence_date_range(absence, day) %></p>
  <% if absence_period(absence) %>
    <p class='period'><%= absence_period(absence) %></p>
  <% end %>
  <% if absence.schedule.active? %>
    <p class='recurring'><%= absence_recurring(absence) %></p>
  <% end %>
  <% if edit %>
  <a href='#' class='small button remote-reveal' data-reveal-id='absence-modal' data-reveal-url='<%= edit_user_absence_path(@user, absence) %>'>
    <%= t('.edit') %>
  </a>
  <% end %>
  <hr>
<% end %>
<% if defined?(user) && can?(:manage, Absence) %>
  <a href='#' class='has-reveal remote-reveal' data-reveal-id='absence-modal' data-reveal-url='<%= new_user_absence_path(user, date: day) %>'><%= t '.add_absence' %></a>
<% end %>
</div>

app/views/shared/_event_legend.html.erb
<ul class="event-legend">
  <% if show_public_holiday %>
  <li>
    <i class="icon-flag public-holiday-color"></i>
    <%= t '.public_holiday' %>
  </li>
  <% end %>

  <% time_types.each do |time_type| %>
  <li>
    <%= icon_for_time_type(time_type) %>
    <%= time_type %>
  </li>
  <% end %>
</ul>

app/views/shared/_nice_modal.html.erb
<div id="time-modal" class="small reveal-modal time">
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/shared/_public_holiday_tooltip.html.erb
<div class='event'>
  <h1>
    <i class='icon-flag public-holiday-color'></i> <%= public_holiday.name %>
  </h1>
  <p class='date-range'><%= l public_holiday.date %></p>
  <% if absence_period(public_holiday) %>
    <p class='period'><%= absence_period(public_holiday) %></p>
  <% end %>
</div>

app/views/shared/_user_select.html.erb
<% if show_user_select? %>
  <div class="row">
    <div class="large-2 columns"><%= t '.user' %></div>
    <div class="large-4 columns">
      <select name="user">
        <% selectable_users.each do |user| %>
          <option data-link="<%= method(link_generator).call(user) %>" <% if user == selected_user %>selected="selected"<% end %>><%= user %></option>
        <% end %>
      </select>
    </div>
    <div class="large-6 columns end"></div>
  </div>
<% end %>