config/routes.rb
Uberzeit::Application.routes.draw do

  year_month_team_id_constraints = {year: /\d+/, month: /\d+/, team_id: /\d+/}

  root :to => 'sessions#new'


  # session stuff
  resource :session, only: [:new, :create, :destroy] do
    put '/language', action: :change_language
  end

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/logout', to: 'sessions#destroy', as: 'logout'


  # users scope
  resources :users do
    member do
      put '/activate', to: 'users#activate', as: 'activate'
      put '/deactivate', to: 'users#deactivate', as: 'deactivate'
    end
    resource :password, only: [:edit, :update]

    resources :recurring_entries, except: [:show, :index]

    resources :absences do
      collection do
        get '/year/:year', to: 'absences#index', as: 'year'
        resources :time_entries, controller: :absence_time_entries, as: :absence_time_entries, only: :create
      end
    end

    get '/comparison/date/:date', to: 'comparison#show', as: :comparison

    resources :time_entries, except: [:show] do
      collection do
        get '/date/:date', to: 'time_entries#index', as: :show_date
        put '/date/:date/stop-timer', to: 'time_entries#stop_timer'

        get '/date/:date/summary', to: 'time_entries#summary_for_date'
      end
    end

    resources :employments
    resources :activities do
      collection do
        get '/date/:date', to: 'activities#index', as: :show_date
      end
    end

    resources :roles, only: [:index, :new, :create, :destroy]
  end

  # management
  resources :public_holidays, except: [:show]
  resources :time_types, except: [:show]
  resources :adjustments, except: [:show]
  resources :projects, except: [:show]
  resources :activity_types, except: [:show]
  resource :configuration, only: [:edit, :update]


  # reporting
  namespace :reports do
    get '/overview/users/:user_id', to: 'overview#index', as: :overview
    get '/work/users/:user_id', to: 'my_work#show', as: :my_work
    get '/work', to: 'work#show', as: :work
    get '/absences', to: 'absence#show'
    get '/absences-calendar', to: 'absence#calendar', as: :absences_calendar
    get '/vacation', to: 'vacation#show'

    namespace :activities do
      get '/billability(/:date)', to: 'billability#index', as: :billability
      get '/billing', to: 'billing#index', as: :billing
      get '/filter', to: 'filter#index', as: :filter
      get '/detailed', to: 'detailed#index', as: :detailed
    end
  end

  resources :teams, except: :show

  resources :customers, except: :show

  # API
  mount API::User => '/api'
  mount API::App => '/api/app'
end

app/models/public_holiday.rb
# == Schema Information
#
# Table name: public_holidays
#
#  id              :integer          not null, primary key
#  date            :date
#  name            :string(255)
#  first_half_day  :boolean          default(FALSE)
#  second_half_day :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  deleted_at      :datetime
#

require_relative 'concerns/dated'

class PublicHoliday < ActiveRecord::Base
  include Dated

  acts_as_paranoid

  default_scope order(:date)

  attr_accessible :first_half_day, :name, :second_half_day, :date, :daypart

  validates_presence_of :name

  validates_datetime :date

  scope_date :date

  after_save :update_days

  def self.half_day_on?(date)
    flag_on_date(date, :half_day?)
  end

  def self.whole_day_on?(date)
    flag_on_date(date, :whole_day?)
  end

  def whole_day?
    not half_day?
  end

  def half_day?
    first_half_day? or second_half_day?
  end
  alias_method :half_day_specific?, :half_day?

  def first_half_day?
    !!first_half_day and not !!second_half_day
  end

  def second_half_day?
    !!second_half_day and not !!first_half_day
  end

  def daypart
    case
    when whole_day?
      :whole_day
    when first_half_day?
      :first_half_day
    when second_half_day?
      :second_half_day
    end
  end

  def daypart=(value)
    case value.to_sym
    when :whole_day
      self.first_half_day = true
      self.second_half_day = true
    when :first_half_day
      self.first_half_day = true
      self.second_half_day = false
    when :second_half_day
      self.first_half_day = false
      self.second_half_day = true
    end
  end

  def on_date?(check_date)
    date == check_date
  end

  def update_days
    changed_dates = [date, date_was].compact
    Day.where(date: changed_dates).each(&:regenerate!)
  end

  private
  def self.flag_on_date(date, flag_sym)
    flag = false
    with_date(date).each do |public_holiday|
      flag ||= public_holiday.send(flag_sym)
    end
    flag
  end
end

app/controllers/public_holidays_controller.rb
class PublicHolidaysController < ApplicationController
  load_and_authorize_resource

  def index
    authorize! :manage, PublicHoliday

    @year = (params[:year] || session[:year] || Time.current.year).to_i
    session[:year] = @year

    @public_holidays = @public_holidays.with_date_in_year(@year)
  end

  def new
  end

  def edit
  end

  def create
    @public_holiday = PublicHoliday.new(params[:public_holiday])
    if @public_holiday.save
      redirect_to public_holidays_path, flash: {success: t('model_successfully_created', model: PublicHoliday.model_name.human)}
    else
      render :action => 'new'
    end
  end

  def update
    @public_holiday = PublicHoliday.find(params[:id])
    if @public_holiday.update_attributes(params[:public_holiday])
      redirect_to public_holidays_path, flash: {success: t('model_successfully_updated', model: PublicHoliday.model_name.human)}
    else
      render :action => 'edit'
    end
  end

  def destroy
    @public_holiday = PublicHoliday.find(params[:id])
    if @public_holiday.destroy
      redirect_to public_holidays_path, flash: {success: t('model_successfully_deleted', model: PublicHoliday.model_name.human)}
    else
      render :action => 'edit'
    end
  end
end

app/views/public_holidays/_form.html.erb
<%= form_for(@public_holiday) do |f| %>
<div class="row">
  <div class="small-4 columns">
    <%= f.text_field :name %>
  </div>
</div>
<div class="row">
  <div class="small-4 columns">
    <%= datefield(f, :date, t('.date'), @public_holiday.date, :date) %>
  </div>
</div>

<div class="row">
  <div class="small-4 columns">
    <%= f.select :daypart, [[t('whole_day'), :whole_day], [t('first_half_day'), :first_half_day], [t('second_half_day'), :second_half_day]] %>
  </div>
</div>

<div class="row">
  <div class="small-3 columns">
    <%= f.submit class: 'button'%>
  </div>
  <div class="small-2 columns end">
    <%= link_to t('.back'), public_holidays_path, class: "secondary button" %>
  </div>
</div>
<% end %>

app/views/public_holidays/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h3><%= t '.title' %></h3>

    <%= render :partial => 'form' %>
  </div>
</div>

app/views/public_holidays/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>
      <%= t '.title', year: @year %>
      <%= link_to icon('caret-left'), public_holidays_path(year: @year - 1) %>
      <%= link_to icon('caret-right'), public_holidays_path(year: @year + 1) %>
      <%= link_to icon('plus') + ' ' + t('.new_public_holiday'), new_public_holiday_path, class: 'button right' %></h3>
    </h1>

    <table class="nice small-12 edit destroy">
      <thead>
        <tr>
          <th><%= PublicHoliday.human_attribute_name :date %></th>
          <th><%= PublicHoliday.human_attribute_name :name %></th>
          <th>&nbsp;</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @public_holidays.each do |public_holiday| %>
          <tr>
            <td>
              <%= l(public_holiday.date, format: :long) %>
            </td>
            <td><%= public_holiday.name %></td>
            <td>
              <%= link_to icon('edit'), edit_public_holiday_path(public_holiday), { title: t('global.actions.edit') } %>
            </td>
            <td>
              <%= link_to icon('trash'), public_holiday, method: :delete, confirm: t('.confirm_delete'), title: t('global.actions.delete') %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/public_holidays/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1><%= t '.title' %></h1>

    <%= render :partial => 'form' %>
  </div>
</div>